### ISSUE TITLE
Sticky header can show a "wrong height" with some plugins

### ISSUE THREAD

**Issue by eri-trabiccolo** [AlxMedia/hueman#598]
https://secure.helpscout.net/conversation/466254820/34335?folderId=607709

As of now the following two pages use the same header image
http://www.hcmolteno.it/
http://www.hcmolteno.it/pallamano-tv/

In the first case the image results cut:
<img width="641" alt="cut-header" src="https://user-images.githubusercontent.com/7689242/32951203-6281db96-cba9-11e7-91fc-4b798b0bab72.png">
while it is not in the second:
<img width="690" alt="full" src="https://user-images.githubusercontent.com/7689242/32951215-6e6e8d3c-cba9-11e7-8dfe-c4232594b594.png">

This happens because in that website's home page an Elementor addon () CSS is loaded (because of the content) which has the following CSS rules:
(without considering the duplication... :))
```css
html {
  box-sizing: border-box; }

*, *::after, *::before {
  box-sizing: inherit; }

html {
  box-sizing: border-box; }

*, *::after, *::before {
  box-sizing: inherit; }
```
(this kind of rule is anyway fairly widespread (e.g. bs uses it) ).

The issue happens because the theme's header has a padding and when we set its height, via js according to the header image, the height will define the whole element's height (borders and paddings included), while we actually want to set its 'content' height (which is the default behavior: all elements have box-sizing: content-box by default).

To avoid this kind of issue we should, at least, specify the header's box-sizing as content-box.

Of course this is a plugin's fault, but since it can happen with a lot of them... we might want to add this prudential compatibility fix.
