### ISSUE TITLE
WooCommerce Related products section CSS issue

### ISSUE THREAD

**Issue by eri-trabiccolo** [AlxMedia/hueman#729]
Reported: 
https://secure.helpscout.net/conversation/724266382/166432?folderId=607541

<img width="1195" alt="screenshot-2018-12-05-at-8 15 21-am" src="https://user-images.githubusercontent.com/7689242/49519269-e679d500-f8a0-11e8-9f45-32aba5fc3346.png">

This is something I remember we had reported in Customizr too.
Basically it happens when the product shows no tabs.
I think it's a WooCommerce fault thuogh...

Though in Customizr we fixed it adding the following rule:
```css
.woocommerce section.related, 
.woocommerce section.up-sells {
    clear: both;
} 
```

Hence we can do the same here.

p.s. in 2017 theme the issue doesn't occur only because the theme style assigns the clear:both to the all the h* (which in this case is Related posts)
