### ISSUE TITLE
Logo + sidebars inconsistencies on iPhone X in landscape

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#810]
> Our Site Logo looks great in customizer when previewed for full size monitor, tablet and smartphone, however, when site is viewed from an iPhone X in landscape (using Chrome) the logo ends in the middle of the site header text.. Seems like a bug to us and we have no idea how to fix this otherwise.

> In landscape mode on an iPhone X, in Chrome, the left and right sidebar controls (>> and <<) to bring the sidebars in won't do anything. This also seems like a bug.Please take a look. Thank You

https://secure.helpscout.net/conversation/905201414/218048?folderId=607547

**Comment by ghost** [comment]
Ah Rocco, there was also this issue I wanted to discuss.
There's a breakpoint issue, in CSS ( and js ? )
https://stackoverflow.com/questions/46313640/iphone-x-8-8-plus-css-media-queries


Let me know if you have ever worked on this type issue ?

## user site
![2019-07-18_12-43-29](https://user-images.githubusercontent.com/3038156/61451458-b4ae0e00-a959-11e9-84c3-9c8c2ca2bd5d.jpg)

## Demo site
![2019-07-18_12-42-34](https://user-images.githubusercontent.com/3038156/61451484-c68fb100-a959-11e9-9f4b-a59820829b31.jpg)

**Comment by eri-trabiccolo** [comment]
Mmm nope...
We probably should take the orientation or the device height into account?!
Anyway the problem with the sidebar controls shouldn't be very tied to it, right?!

**Comment by eri-trabiccolo** [comment]
I'm not able to reproduce the issue on the user website anymore...
 The user found a solution adding the following CSS:
```css
@media all and (min-width:720px)  {
    .site-title {
	  width: 250px;
	  margin-top: -75px;
	  margin-left: -75px;
    }
}
```
Removing that code:
- the logo is positioned as per your screensthot (user site);
- the `#header` height (which is dynamically calculated) becomes bigger than the `#ha-large-header` height, hence the logo "overflows" the large-header.
The #header also overlaps the #page (sidebars main container) and because of the z-index determined by the following CSS in hph-front:
```css
@media only screen and (min-width: 720px) {
    .pro-header-on #header {
         padding-bottom: 0;
         background: 0 0;
         position: absolute;
         z-index: 10000;
         width: 100%; 
    }
}
```
makes the sidebars togglers not accessible. For this last issue a solution would be, adding the following CSS (*):
```css
@media only screen and (min-width: 720px) {
    .pro-header-on #ha-large-header + #page { 
        position: relative;
        z-index: 10000;
    }
}
```

I have no solution for the logo issue though...
Shall we force the #ha-large-header height to be the maximum among the user's choice and the header's height?
Anyway, the solution in (*) will also hide the part of the header that "overflows" the `#ha-large-header`:
![Schermata 2019-07-23 alle 10 12 59](https://user-images.githubusercontent.com/7689242/61694786-80a86380-ad32-11e9-8402-52dd354faf29.png)


p.s.
I write "overflows" (surrounded by quotes) because it's just a visual effect since `#ha-large-header` doesn't contain the `#header`.
