### ISSUE TITLE
[Bug] Some outdated styles (hu-pad / excerpt) break the adaptive layout

### ISSUE THREAD

**Issue by Azure99** [AlxMedia/hueman#865]
I have found these parts
maybe more...
```css
#footer .hu-pad { padding-bottom: 30px; }

@media only screen and (max-width: 719px) {
    .post-standard.excerpt .post-inner { padding-left: 120px; }
    .post-standard.excerpt .post-thumbnail { margin-left: -120px; max-width: 100px; }
    .page-title.hu-pad { padding-top: 12px; padding-bottom: 12px; }
    .hu-pad { padding: 20px 20px 10px; }
    #header .hu-pad { padding-top: 0; padding-bottom: 0; }
    #footer-bottom .hu-pad { padding-top: 50px; padding-bottom: 40px; }

}

@media only screen and (max-width: 479px) {
    .post-standard.excerpt .post-inner { padding-left: 82px; }
    .post-standard.excerpt .post-thumbnail { margin-left: -82px; max-width: 72px; }
    .hu-pad { padding: 15px 15px 5px; }
}
```
