### ISSUE TITLE
[RTL] implement a set of adaptation in a specific stylesheet

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#886]
see https://github.com/presscustomizr/hueman/issues/412

Start with this proposition from a user ( https://secure.helpscout.net/conversation/1144240533/221010/ ) 

> 
> These are all I have fixed in a couple of minutes of skimming pages. I didn't have time to check everything but it could be good for the start :)
> 
> And I strongly suggest having some RTL custom fonts. I personally like Vazir because it is very clean.

``` CSS
@import url('https://cdn.rawgit.com/rastikerdar/vazir-font/v24.2.0/dist/font-face.css');

html, body {
font-family: 'Vazir', sans-serif;
}

.site-title {
float: right;
}
.site-description {
float: right;
margin-right: 20px;
margin-left: 0;
}

.sidebar-top p {
float: right;
}

.widget > div > ul li a::before, .widget > ul li a::before, .widget > ul li::before, .widget_calendar caption::before {
margin-right: 0;
margin-left: 6px;
}

.nav > li > a::after {
margin-left: 0;
margin-right: 6px;
}

.alignright, .right {
float: left;
}

.alignleft, .left {
float: right;
}

.grid {
margin-left: 3.2%;
margin-right: 0;
float: right;
}

.last {
clear: left;
margin-left: 0 !important;
margin-right: auto;
}

.heading i {
margin-right: 0;
margin-left: 6px;
}
```
