### ISSUE TITLE
[TRT requirement][accessibility] Links within content must be underlined 

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#936]
https://make.wordpress.org/themes/handbook/review/required/#links-within-content-must-be-underlined

> When links appear within a larger body of block-level content, they must be clearly distinguishable from surrounding content (**Post content, comment content, text widgets, custom options with large blocks of texts)**.
> Links in navigation-like contexts (e.g. menus, lists of upcoming posts in widgets, grouped post meta data) do not need to be specifically distinguished from surrounding content.
> 
> **The underline is the only accepted method of indicating links within content**. Bold, italicized, or color-differentiated text is ambiguous and will not pass.

Rules to add
```CSS
article .entry-content a, .comment-content a, .widget-area .widget_text a {
  text-decoration:underline;
}
```

https://wptavern.com/themes-team-removes-outdated-css-guidelines-adds-stricter-requirement-for-links-in-content
